help: 
	@echo "Commands:"
	@echo " - help: 	show this help"
	@echo " - new:		create a new file for today"

setup: 
	@touch session.cookie
	@mkdir -p input
	@make help

new: 
	@python3 utils/new_day.py